//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Composite.Community.TellAFriend.Package.Package.App_GlobalResources.Composite.Community {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TellAFriend {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TellAFriend() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Composite.Community.TellAFriend.Package.Package.App_GlobalResources.Composite.Com" +
                            "munity.TellAFriend", typeof(TellAFriend).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write the text from the picture.
        /// </summary>
        internal static string captcha {
            get {
                return ResourceManager.GetString("captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text you typed in did not match the image. Please try again..
        /// </summary>
        internal static string captchaError {
            get {
                return ResourceManager.GetString("captchaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &lt;br/&gt; Read it here  {1}.
        /// </summary>
        internal static string emailBody {
            get {
                return ResourceManager.GetString("emailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interesting page at.
        /// </summary>
        internal static string emailSubject {
            get {
                return ResourceManager.GetString("emailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From e-mail.
        /// </summary>
        internal static string fromEmail {
            get {
                return ResourceManager.GetString("fromEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid from e-mail..
        /// </summary>
        internal static string fromEmailError {
            get {
                return ResourceManager.GetString("fromEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From name.
        /// </summary>
        internal static string fromName {
            get {
                return ResourceManager.GetString("fromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a from name, the field cannot be empty..
        /// </summary>
        internal static string fromNameError {
            get {
                return ResourceManager.GetString("fromNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The STMP configuration was not found in web.config – please refer to the documentation..
        /// </summary>
        internal static string missingSMTP {
            get {
                return ResourceManager.GetString("missingSMTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell a friend.
        /// </summary>
        internal static string tellAFriend {
            get {
                return ResourceManager.GetString("tellAFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you!.
        /// </summary>
        internal static string thankYou {
            get {
                return ResourceManager.GetString("thankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To e-mail.
        /// </summary>
        internal static string toEmail {
            get {
                return ResourceManager.GetString("toEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid to e-mail..
        /// </summary>
        internal static string toEmailError {
            get {
                return ResourceManager.GetString("toEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To name.
        /// </summary>
        internal static string toName {
            get {
                return ResourceManager.GetString("toName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a to name, the field cannot be empty..
        /// </summary>
        internal static string toNameError {
            get {
                return ResourceManager.GetString("toNameError", resourceCulture);
            }
        }
    }
}
