///<reference path='../Generics/Collections/IHashTable.ts' />

module Orckestra.Composer {
    /*
    * This is the collection of compiled Handlebars templates. The templates are
    * generated by the build process. This is here only to appease TypeScript.
     */
    export interface IComposerTemplates {
        Templates: IHashTable<Function>;
    }
}
