#!/usr/bin/env node

var path   = require('path'),
    sys	   = require('util'),
    sass   = require(path.join(__dirname, 'sass')),
    inFile = process.argv[2];

var currentErrorcode = 0;

// calling process.exit does not flush stdout always so use this to set the exit code
process.on('exit', function() { process.reallyExit(currentErrorcode) });

// Render scss file
sass.render({
  file: inFile,
  
  success: function(css) {
    sys.print(css);
  },

  error: function(err) {
    currentErrorcode = 2;
    sys.print('Error Rendering SASS: ' + err);
  }
});