//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Composite.Community.Blog.Package.Package.App_GlobalResources.Composite.Community {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Blog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Blog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Composite.Community.Blog.Package.Package.App_GlobalResources.Composite.Community." +
                            "Blog", typeof(Blog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Captcha value.
        /// </summary>
        internal static string captchaError {
            get {
                return ResourceManager.GetString("captchaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write the text from the image.
        /// </summary>
        internal static string commentCaptchaFiledText {
            get {
                return ResourceManager.GetString("commentCaptchaFiledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string commentCommentFieldText {
            get {
                return ResourceManager.GetString("commentCommentFieldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string commentEmailFieldText {
            get {
                return ResourceManager.GetString("commentEmailFieldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Comment value.
        /// </summary>
        internal static string commentError {
            get {
                return ResourceManager.GetString("commentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string commentNameFieldText {
            get {
                return ResourceManager.GetString("commentNameFieldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMENTS.
        /// </summary>
        internal static string commentsText {
            get {
                return ResourceManager.GetString("commentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Your Comment.
        /// </summary>
        internal static string commentsTitleText {
            get {
                return ResourceManager.GetString("commentsTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string commentTitleFieldText {
            get {
                return ResourceManager.GetString("commentTitleFieldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct the errors below:.
        /// </summary>
        internal static string correctErrorsText {
            get {
                return ResourceManager.GetString("correctErrorsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect E-mail value.
        /// </summary>
        internal static string emailError {
            get {
                return ResourceManager.GetString("emailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Name value.
        /// </summary>
        internal static string nameError {
            get {
                return ResourceManager.GetString("nameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string SendButton {
            get {
                return ResourceManager.GetString("SendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBJECTS:.
        /// </summary>
        internal static string subjectsText {
            get {
                return ResourceManager.GetString("subjectsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Title value.
        /// </summary>
        internal static string titleError {
            get {
                return ResourceManager.GetString("titleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WRITTEN BY.
        /// </summary>
        internal static string writtenByText {
            get {
                return ResourceManager.GetString("writtenByText", resourceCulture);
            }
        }
    }
}
