//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orckestra.Widget.FilteredSelector.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class default_text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal default_text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orckestra.Widget.FilteredSelector.Resources.default_text", typeof(default_text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received parameters {0} are invalid..
        /// </summary>
        internal static string FilteredSelectorWidgetProcManEx1 {
            get {
                return ResourceManager.GetString("FilteredSelectorWidgetProcManEx1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to create data elements selecting rules, depending on current element page reference..
        /// </summary>
        internal static string SelectFilteredDataWidgetFuncDescr {
            get {
                return ResourceManager.GetString("SelectFilteredDataWidgetFuncDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot receive sitemapscope param..
        /// </summary>
        internal static string SelectFilteredDataWidgetFuncEx01 {
            get {
                return ResourceManager.GetString("SelectFilteredDataWidgetFuncEx01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilteredSelector.
        /// </summary>
        internal static string SelectFilteredDataWidgetFuncName {
            get {
                return ResourceManager.GetString("SelectFilteredDataWidgetFuncName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select sitemap scope for filtering.
        /// </summary>
        internal static string SelectFilteredDataWidgetFuncSitescopeHelp {
            get {
                return ResourceManager.GetString("SelectFilteredDataWidgetFuncSitescopeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serializes page id, scope id and datatype name in markup to pass it as a composed param to a static function call.
        /// </summary>
        internal static string SerializeMarkupParamsFuncDescr {
            get {
                return ResourceManager.GetString("SerializeMarkupParamsFuncDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SerializePageRelatedMarkupParams.
        /// </summary>
        internal static string SerializeMarkupParamsFuncName {
            get {
                return ResourceManager.GetString("SerializeMarkupParamsFuncName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define guid of page.
        /// </summary>
        internal static string SerializeMarkupParamsFuncPageIdHelp {
            get {
                return ResourceManager.GetString("SerializeMarkupParamsFuncPageIdHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define int code of sitemap scope.
        /// </summary>
        internal static string SerializeMarkupParamsFuncSitemapScopeIdHelp {
            get {
                return ResourceManager.GetString("SerializeMarkupParamsFuncSitemapScopeIdHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define full name of type including namespace.
        /// </summary>
        internal static string SerializeMarkupParamsFuncTypeNameHelp {
            get {
                return ResourceManager.GetString("SerializeMarkupParamsFuncTypeNameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All pages (no filter).
        /// </summary>
        internal static string SitemapScope_All {
            get {
                return ResourceManager.GetString("SitemapScope_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancestor pages.
        /// </summary>
        internal static string SitemapScope_Ancestors {
            get {
                return ResourceManager.GetString("SitemapScope_Ancestors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancestors and current (breadcrumb).
        /// </summary>
        internal static string SitemapScope_AncestorsAndCurrent {
            get {
                return ResourceManager.GetString("SitemapScope_AncestorsAndCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child pages.
        /// </summary>
        internal static string SitemapScope_Children {
            get {
                return ResourceManager.GetString("SitemapScope_Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current page.
        /// </summary>
        internal static string SitemapScope_Current {
            get {
                return ResourceManager.GetString("SitemapScope_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descendant pages.
        /// </summary>
        internal static string SitemapScope_Descendants {
            get {
                return ResourceManager.GetString("SitemapScope_Descendants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current and descendant pages.
        /// </summary>
        internal static string SitemapScope_DescendantsAndCurrent {
            get {
                return ResourceManager.GetString("SitemapScope_DescendantsAndCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 1 page (homepage).
        /// </summary>
        internal static string SitemapScope_Level1 {
            get {
                return ResourceManager.GetString("SitemapScope_Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 1 and descendant pages (current site).
        /// </summary>
        internal static string SitemapScope_Level1AndDescendants {
            get {
                return ResourceManager.GetString("SitemapScope_Level1AndDescendants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 1 and sibling pages (all homepages).
        /// </summary>
        internal static string SitemapScope_Level1AndSiblings {
            get {
                return ResourceManager.GetString("SitemapScope_Level1AndSiblings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 2 page.
        /// </summary>
        internal static string SitemapScope_Level2 {
            get {
                return ResourceManager.GetString("SitemapScope_Level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 2 and descendant pages.
        /// </summary>
        internal static string SitemapScope_Level2AndDescendants {
            get {
                return ResourceManager.GetString("SitemapScope_Level2AndDescendants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 2 and sibling pages (site main areas).
        /// </summary>
        internal static string SitemapScope_Level2AndSiblings {
            get {
                return ResourceManager.GetString("SitemapScope_Level2AndSiblings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 3 page.
        /// </summary>
        internal static string SitemapScope_Level3 {
            get {
                return ResourceManager.GetString("SitemapScope_Level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 3 and descendant pages.
        /// </summary>
        internal static string SitemapScope_Level3AndDescendants {
            get {
                return ResourceManager.GetString("SitemapScope_Level3AndDescendants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 3 and sibling pages.
        /// </summary>
        internal static string SitemapScope_Level3AndSiblings {
            get {
                return ResourceManager.GetString("SitemapScope_Level3AndSiblings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 4 page.
        /// </summary>
        internal static string SitemapScope_Level4 {
            get {
                return ResourceManager.GetString("SitemapScope_Level4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 4 and descendant pages.
        /// </summary>
        internal static string SitemapScope_Level4AndDescendants {
            get {
                return ResourceManager.GetString("SitemapScope_Level4AndDescendants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 4 and sibling pages.
        /// </summary>
        internal static string SitemapScope_Level4AndSiblings {
            get {
                return ResourceManager.GetString("SitemapScope_Level4AndSiblings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent page.
        /// </summary>
        internal static string SitemapScope_Parent {
            get {
                return ResourceManager.GetString("SitemapScope_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sibling pages.
        /// </summary>
        internal static string SitemapScope_Siblings {
            get {
                return ResourceManager.GetString("SitemapScope_Siblings", resourceCulture);
            }
        }
    }
}
